{
 "title": "MLOps — Image Classifier",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(predict_requests_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(predict_requests_total{status='success'}) / sum(predict_requests_total) * 100",
     "legendFormat": "Success %"
    }
   ]
  },
  {
   "title": "Avg Latency (ms)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(predict_latency_seconds_sum[1m]) / rate(predict_latency_seconds_count[1m]) * 1000",
     "legendFormat": "Avg Latency"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(predict_requests_total{status='error'})",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Request Rate (req/min)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rate(predict_requests_total{status='success'}[1m]) * 60",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(predict_requests_total{status='error'}[1m]) * 60",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Latency Distribution (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(predict_latency_seconds_bucket[1m])) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(predict_latency_seconds_bucket[1m])) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(predict_latency_seconds_bucket[1m])) * 1000",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Prediction Distribution by Class",
   "type": "piechart",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    { "expr": "prediction_class_total", "legendFormat": "{{class_name}}" }
   ]
  },
  {
   "title": "Class Predict Over Time",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rate(prediction_class_total[1m]) * 60",
     "legendFormat": "{{class_name}}"
    }
   ]
  }
 ]
}